---
format:
  pdf:
    engine: xelatex
    documentclass: article
    classoption: [12pt, a4paper]
    header-includes: |
      \usepackage{fontspec}
      \setmainfont{Times New Roman}
      \usepackage[margin=2.0cm]{geometry}
      \usepackage{setspace}
      \doublespacing
      \usepackage{hyperref}
      \usepackage[nottoc]{tocbibind}
      \usepackage[nopostdot, acronym]{glossaries}
      \makeglossaries
      \setlength{\glsdescwidth}{0.8\textwidth}
      \AtBeginDocument{
        \title{My Template}
        \maketitle
        \begin{center}
          {\author{Example}}
          {\date{\today}}
        \end{center}
        \clearpage
        \pagenumbering{roman}
        \clearpage
      }
      \AtEndDocument{
        \clearpage
        \listoftables
        \clearpage
        \listoffigures
      }
    toc: true
    toc-depth: 2
editor: visual
---

```{r}
#| label: installLoadPackages
#| warning: false
#| message: false
#| include: false

# Required packages
requiredPackages <- c("tidyverse", "reticulate", "scales", "readxl")

# Function to check if packages are installed
installPackages <- function(pkg) {
  if(!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE, quiet = FALSE)
  }
}

# Install packages if not found on local
invisible(sapply(requiredPackages, installPackages))

# Load packages
invisible(lapply(requiredPackages, library, character.only = TRUE))
```

```{r}
#| label: installPythonPackages
#| warning: false
#| messaage: true
#| include: false

# Include the required packages
pythonPackages <- c('numpy', 'pandas', 'seaborn', 'matplotlib', 'statsmodels', 'scienceplots')

# Function to check whether the packages / modules have been installed
installPythonPackages <- function(packages) {
  for(pkg in packages) {
    if(!reticulate::py_module_available(pkg)) {
      message("Installing Python packages ", pkg)
      reticulate::py_install(pkg, pip = FALSE)
    } else {
      message("Python package ", pkg, "is already installed")
    }
  }
}

# Install packages
installPythonPackages(pythonPackages)
```

```{python}
#| label: loadPythonModules
#| message: false
#| warning: false
#| include: false

# Import python modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import scienceplots
import seaborn as sns
```

```{python}
#| label: fig-pythonExample
#| fig-cap: 'Provide a caption for the python generated figure!'
#| fig-pos: 'H'
#| echo

# Plot a python figure here!
```

```{r}
#| label: fig-rExample
#| fig-cap: 'Provide a caption for the r generated figure!'
#| fig-pos: 'H'

# Plot a r figure here!
```

\newpage

# Introduction:

# Background:

# Knowledge: Current and Gaps:

# Relevance: 
